# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-20 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django_jsonschema.postgres.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.PositiveIntegerField()),
                ('content', django_jsonschema.postgres.models.JSONSchemaField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
